### ISSUE TITLE
automatically reserving all the beds in the room, if the room is reserved

### ISSUE THREAD

**Issue by logicsandeep** [hmis-api/bed-and-housing-management#10]
We have APIs for room registration does it automatically reserve all the beds in the room ?

**Comment by suryayadavalli** [comment]
From @eric-jahn: I think the problem @sandeep.dolia is discovering is that because we made rooms an aggregation of beds, like in /shelters/rooms/ beds, we need to block out all the beds if the room is reserved or booked.  Otherwise, if we don't, someone could reserve /shelter 1/room 1, but then someone else might try to later reserve /shelter 1/room 1/beds 1-3, because we didn't also reserve beds 1-3 when the room 1 that contains them was reserved.

**Comment by suryayadavalli** [comment]
** Work in progress **  
ETA for deployment 12/11

**Comment by suryayadavalli** [comment]
commit id : https://github.com/servinglynk/hslynk-open-source/commit/499d565db149a3eef9d012cda93c92e4569976a6

**Comment by logicsandeep** [comment]
@suryayadavalli / @eric-jahn , 
 I don't think we should reserve all the beds in the room when we reserve a client to a room because this contradicts our agreement about issue #12. In case of an overflow (or emergency), we decided to reserve/check-in clients to a room, and reserving a room would cause a reservation to all the beds and we don't want that.

**Comment by logicsandeep** [comment]
This commit needs to be rolled back.

**Comment by eric-jahn** [comment]
@logicsandeep would it be possible, in the situation you describe, to not
reserve a client to the entire room, but reserve them to just a single bed
in the room?

Eric Jahn

**Comment by logicsandeep** [comment]
@eric-jahn  If a caseworker wants to reserve a bed then we already have a bed reservation API.  And that's true we don't want all the rooms reserved for the same client.

**Comment by eric-jahn** [comment]
~I'm wondering if we should even have room reservations.  If we do keep room reservations, when a room is reserved to a single client, what should happen is that one of the beds in the room should be reserved for that client, and all the other available beds are changed to unavailable.  So either we remove the room reservation API, or we change how it works.~

**Comment by eric-jahn** [comment]
~For virtual beds, just check the person into a new virtual bed.  POST the room/id/beds, set it to virtual, and check them into it.~

**Comment by suryayadavalli** [comment]
@eric-jahn : Reserving a room (instead reserving a bed unit) for client should indicate that its a virtual bed scenario. As we discussed earlier, we can simply assign the room to the client without reserving the bed units in this scenario.  

So, if we make room reservations for 100 clients, it indicates that we are accommodating all these clients in that room. There is no limit to how many clients since in cases of natural calamities, I think a room can accommodate more than what it's ideal capacity.

**Comment by eric-jahn** [comment]
@suryayadavalli This makes sense.  And then, in the future, we can have duplicate checkin/reservation validation at the project level.

**Comment by logicsandeep** [comment]
This is not required.
